version: '3.8'

services:
  flask:
    build:
      context: ./backend_data
    ports:
      - "5000:5000"
    volumes:
      - ./backend_data:/app
    depends_on: 
      - chromadb
    hostname: mflask

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    hostname: mymongo

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      CHROMA_DB_HOST: 0.0.0.0  # Allow external access
      CHROMA_DB_PORT: 8000
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    hostname: mychroma

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    tty: true
    stdin_open: true
    volumes:
      - kali_data:/root  # Persist data in the /root directory      

  react-frontend:
    build:
      context: ./frontend_data # Make sure this path is correct
    container_name: frontend_react
    ports:
      - "5173:5173" # Make sure Vite is set to run on this port
    volumes:
      - ./frontend_data:/usr/src/app
    environment:
      - VITE_HOST=0.0.0.0 # Ensure Vite binds to all network interfaces
    restart: unless-stopped


  ia_negocios:
    image: ollama/ollama
    container_name: ia_negocios_ollama
    ports:
      - "11434:11434"
    hostname: myollama

volumes:
  chroma_data:
  mongo_data:
  backend_data:
  kali_data:

